version: '3.8'
services:
  mysql:
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB_NAME}
      MYSQL_USER: remote_user
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal

  web:
    command: gunicorn --workers 1  -t 90 --bind 0.0.0.0:8081 uwsgi:app --log-level=debug
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      FLASK_APP: uwsgi.py
      FLASK_ENV: production
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      SQL_HOSTNAME: mysql
      SQL_USERNAME: remote_user
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      CRYPT_KEY: ${CRYPT_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
    volumes:
      - ./app:/rawcon/app
      - ./app/static:/rawcon/app/static
      - ./config.py:/rawcon/config.py
      - ./uwsgi.py:/rawcon/uwsgi.py
    depends_on:
      - mysql
    networks:
      - appnet
      - internal

volumes:
  db_volume:
  user_files_volume:  # New volume for user files

networks:
    internal:
      driver: "bridge"
    appnet:
      external: true
