"""eula acceptance, removed recent tracks column

Revision ID: 4bff487b0fe5
Revises: 2b53abf911d5
Create Date: 2024-12-19 17:56:41.250021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bff487b0fe5'
down_revision = '2b53abf911d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eula_accepted', sa.Boolean(), nullable=True))
        batch_op.drop_column('recent_tracks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recent_tracks', mysql.JSON(), nullable=True))
        batch_op.drop_column('eula_accepted')

    # ### end Alembic commands ###
