"""initial schema

Revision ID: 52e8cca91ea4
Revises: 
Create Date: 2024-11-24 03:59:18.494342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e8cca91ea4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_data', schema=None) as batch_op:
        batch_op.drop_constraint('feature_data_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'artist_data', ['artist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('playlist_data', schema=None) as batch_op:
        batch_op.drop_constraint('playlist_data_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['spotify_user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('playlist_data_ibfk_1', 'user_data', ['user_id'], ['spotify_user_id'])

    with op.batch_alter_table('feature_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('feature_data_ibfk_1', 'artist_data', ['artist_id'], ['id'])

    # ### end Alembic commands ###
