"""rels

Revision ID: a81d5b47ecf5
Revises: 
Create Date: 2024-08-31 16:59:44.948618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a81d5b47ecf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_data_name'), ['name'], unique=False)

    with op.batch_alter_table('feature_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_feature_data_artist_id'), ['artist_id'], unique=False)
        batch_op.create_foreign_key(None, 'artist_data', ['artist_id'], ['id'])

    with op.batch_alter_table('playlist_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_playlist_data_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_data_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_data', ['user_id'], ['spotify_user_id'])

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('playlist_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_playlist_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_data_name'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('feature_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_feature_data_artist_id'))
        batch_op.drop_column('artist_id')

    with op.batch_alter_table('artist_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_data_name'))

    # ### end Alembic commands ###
